export enum EventType {
  TOURNAMENT_PAIRS = "TOURNAMENT_PAIRS",
  TOURNAMENT_TEAMS = "TOURNAMENT_TEAMS",
  LEAGUE_MEETING = "LEAGUE_MEETING",
  TRAINING = "TRAINING",
  OTHER = "OTHER",
}

export enum TournamentType {
  MAX = "MAX",
  IMPS = "IMPS",
  CRAZY = "CRAZY",
  BAMY = "BAMY",
}
